name: Build and Deploy Java App to ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: sandrakumi-javaapp

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test --no-transfer-progress

      - name: Generate test report
        run: mvn surefire-report:report --no-transfer-progress
        if: always()

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    name: Build and Push to ECR
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if it doesn't exist
        run: |
          echo "🏗️ Ensuring ECR repository exists..."
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region $AWS_REGION 2>/dev/null || \
          aws ecr create-repository --repository-name $ECR_REPOSITORY --region $AWS_REGION
          echo "✅ Repository ready"

      - name: Build application
        run: |
          echo "🔨 Building Java application..."
          mvn clean package -DskipTests --no-transfer-progress
          echo "✅ Build completed successfully"

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "🐳 Building Docker image..."

          # Build Docker image once
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          # Tag the same image with different tags
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME

          echo "📤 Pushing images to ECR..."

          # Push all tags
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME

          echo "✅ Images pushed successfully!"
          echo ""
          echo "🔗 Image URIs:"
          echo "   - $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "   - $ECR_REGISTRY/$ECR_REPOSITORY:latest"
          echo "   - $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME"

      - name: Test Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "🧪 Testing Docker image..."
          
           # Run container in detached mode
          docker run -d --name test-container -p 8080:8080 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          echo "⏳ Waiting for the application to become healthy..."
          
          # Set a timeout of 2 minutes
          end_time=$(( $(date +%s) + 120 ))
          
          # Loop until the health endpoint responds with a 2xx status or we time out
          while true; do
            # Use curl's --fail flag to exit with an error on non-2xx responses.
            # We check the /health endpoint, which is standard for this purpose.
            curl -s --fail http://localhost:8080/health > /dev/null
          
            # Check the exit status of the curl command
            if [ $? -eq 0 ]; then
              echo "✅ Application is healthy and responding."
              break
            fi
          
            # Check for timeout
            if [ $(date +%s) -gt $end_time ]; then
              echo "❌ Timeout: Application did not become healthy within 2 minutes."
              echo "Container logs:"
              docker logs test-container
              exit 1
            fi
          
            echo "   - Application not ready yet. Retrying in 5 seconds..."
            sleep 5
          done
          
          # At this point, the application is confirmed to be running.
          # You can run additional tests if needed.
          echo "✅ All tests passed!"
          
          # Cleanup
          echo "🧹 Cleaning up test container..."
          docker stop test-container
          docker rm test-container

      - name: Image vulnerability scan
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "🔍 Scanning image for vulnerabilities..."
          
          # Install Trivy
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          
          # Scan image
          trivy image --exit-code 0 --severity HIGH,CRITICAL $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          echo "🔒 Security scan completed"