name: Build and Deploy Java App to ECR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: sandrakumi-javaapp

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test --no-transfer-progress

      - name: Generate test report
        run: mvn surefire-report:report --no-transfer-progress
        if: always()

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    name: Build and Push to ECR
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if it doesn't exist
        run: |
          echo "🏗️ Ensuring ECR repository exists..."
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region $AWS_REGION 2>/dev/null || \
          aws ecr create-repository --repository-name $ECR_REPOSITORY --region $AWS_REGION
          echo "✅ Repository ready"

      - name: Build application
        run: |
          echo "🔨 Building Java application..."
          mvn clean package -DskipTests --no-transfer-progress
          echo "✅ Build completed successfully"

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "🐳 Building Docker image..."

          # Build Docker image once
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          # Tag the same image with different tags
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME

          echo "📤 Pushing images to ECR..."

          # Push all tags
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME

          echo "✅ Images pushed successfully!"
          echo ""
          echo "🔗 Image URIs:"
          echo "   - $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "   - $ECR_REGISTRY/$ECR_REPOSITORY:latest"
          echo "   - $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME"

      - name: Test Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "🧪 Testing Docker image..."
          
          # Run container in detached mode with health check
          docker run -d --name test-container -p 8080:8080 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Wait for container to start and check if it's running
          echo "Waiting for container to start..."
          sleep 10
          
          # Check container status
          if ! docker ps | grep test-container; then
            echo "❌ Container failed to start!"
            echo "Container logs:"
            docker logs test-container
            docker rm test-container
            exit 1
          fi
          
          # Wait longer for Spring Boot to fully initialize
          echo "Waiting for Spring Boot to initialize..."
          sleep 45
          
          # Function to test endpoints with retries
          test_endpoint() {
            local url=$1
            local max_attempts=5
            local attempt=1
          
            while [ $attempt -le $max_attempts ]; do
              echo "Testing $url (attempt $attempt/$max_attempts)..."
          
              # Use different curl options to handle chunked responses better
              response=$(curl -s -w "%{http_code}|%{response_code}" --max-time 30 --connect-timeout 10 "$url" 2>/dev/null || echo "000|connection_failed")
              http_code=$(echo "$response" | tail -c 4)
          
              if [ "$http_code" = "200" ]; then
                echo "✅ $url responded with HTTP $http_code"
                return 0
              else
                echo "⚠️ Attempt $attempt failed for $url (HTTP code: $http_code)"
                if [ $attempt -eq $max_attempts ]; then
                  echo "❌ All attempts failed for $url"
                  echo "Container logs:"
                  docker logs test-container
                  return 1
                fi
                sleep 10
                attempt=$((attempt + 1))
              fi
            done
          }
          
          # Alternative function using wget as fallback
          test_endpoint_wget() {
            local url=$1
            echo "Testing $url with wget..."
          
            if wget --timeout=30 --tries=1 -O /dev/null -q "$url"; then
              echo "✅ $url responded successfully (wget)"
              return 0
            else
              echo "❌ $url failed (wget)"
              return 1
            fi
          }
          
          # Test endpoints with both methods
          echo "Testing endpoints..."
          
          # Test root endpoint
          if ! test_endpoint "http://localhost:8080/"; then
            echo "Retrying with wget..."
            test_endpoint_wget "http://localhost:8080/" || exit 1
          fi
          
          # Test health endpoint  
          if ! test_endpoint "http://localhost:8080/health"; then
            echo "Retrying with wget..."
            test_endpoint_wget "http://localhost:8080/health" || exit 1
          fi
          
          # Test API info endpoint
          if ! test_endpoint "http://localhost:8080/api/info"; then
            echo "Retrying with wget..."
            test_endpoint_wget "http://localhost:8080/api/info" || exit 1
          fi
          
          # Additional verification - check if the container is still running
          if ! docker ps | grep test-container; then
            echo "❌ Container stopped running during tests!"
            echo "Container logs:"
            docker logs test-container
            exit 1
          fi
          
          # Show a sample response for debugging
          echo "📄 Sample response from root endpoint:"
          curl -s --max-time 10 "http://localhost:8080/" | head -c 500 || echo "Could not retrieve sample response"
          
          # Cleanup
          docker stop test-container
          docker rm test-container
          
          echo "✅ All tests passed!"

      - name: Image vulnerability scan
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "🔍 Scanning image for vulnerabilities..."
          
          # Install Trivy
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
          
          # Scan image
          trivy image --exit-code 0 --severity HIGH,CRITICAL $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          echo "🔒 Security scan completed"